apiVersion: batch/v1
kind: Job
metadata:
  name: non-parallel-job
spec:
  template:
    spec:
      containers:
      - name: task-container
        image: busybox
        command: ["echo", "Hello from non-parallel job"]
      restartPolicy: Never
  backoffLimit: 4
