apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  parallelism: 2
  completions: 4
  template:
    spec:
      containers:
      - name: task-container
        image: busybox
        command: ["echo", "Hello from parallel job"]
      restartPolicy: Never
  backoffLimit: 4
