apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduled-job
spec:
  schedule: "*/1 * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task-container
            image: busybox
            command: ["echo", "Hello from scheduled job"]
          restartPolicy: OnFailure
